version: 2
updates:
  # Enable version updates for Composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "beegoodit"
    labels:
      - "dependencies"
      - "composer"
    commit-message:
      prefix: "chore"
      include: "scope"

